version: 2.1
orbs: 
  node: circleci/node@4.9.0
jobs:
  lint:
    executor:
      name: node/default
      tag: '14.18.2'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run Lint
workflows:
  kubevirt_lint:
    jobs:
      - lint
